name: Update HTML

on:
  push:
    branches:
      - main  # Adjust if you're using a different branch

permissions:
  contents: write

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        npm install csv-parser fs

    - name: Generate HTML from CSV
      run: |
        node generate_html.js

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add index.html
        git commit -m "Update index.html with new publications"
        git push